WINDOW_WIDTH = 640
WINDOW_HEIGHT = 640
TILESIZE = 32
FPS = 60

PLAYER_LAYER = 4
GHOST_LAYER = 3
DOT_LAYER = 2
BLOCK_LAYER = 1
SPEED = 3

RED = (255,0,0)
BLUE = (0,0,255)
BLACK = (0,0,0)


TILEMAP = [
'WWWWWWWWWWWWWWWWWWWW',
'W........W.........W',
'W.WW.WWW.W.WWWW.WW.W',
'W..................W',
'W.WW.W.WWWWW.W.WWW.W',
'W....W...W.........W',
'WWWW.WWW.W.WWWWWWWWW',
'WWWW...........WWWWW',
'WWWW.WWWW-WWWW.WWWWW',
'W....WpScSBSiW.....W',
'W.WWWWWWWWWWWWWWWW.W',
'W.WWW..........WWW.W',
'W.....WWWWWWWW.....W',
'WWWWW....U.....WWWWW',
'W.....WWWWWWWW.....W',
'W.WWWW...W....WWWW.W',
'W.WWWW.W.W.WW.WWWW.W',
'W.WWWW.W.W.WW.WWWW.W',
'W..................W',
'WWWWWWWWWWWWWWWWWWWW'
]